### PR TITLE
fix: CPython engine init failure - version format mismatch in EnvDict…

### LINKED ISSUE #3284: [Bug]: Cpython doesnt work in pyRevit v6.4.0
### ✈ Pre-Flight checks

- [x] I **don't have SentinelOne** antivirus installed (see above for the solution)
- [x] I have **searched in the issues** (open and closed) but couldn't find a similar issue
- [x] I have **searched in the [pyRevit Forum](https://discourse.pyrevitlabs.io)** for similar issues
- [x] I already **followed the [installation troubleshooting guide](https://pyrevitlabs.notion.site/Installation-issues-f6495adb56254e9e8021f8a68e3b2ab7) thoroughly**
- [x] I am using the **latest pyRevit Version**

### 🐞 Describe the bug

when runing a cpython script im getting an error prompt

### ⌨ Error/Debug Message

```shell
when runing a CPython script, for ex. Test CPython command (from pyRevitDev): "Revit could not complete the external command..Revit encountered a The type initializer for wDeligatesw threw an exception".
when runing test CPython engine. the output window shows:
C:\Users\betsalel\AppData\Roaming\pyRevit-Master\extensions\pyRevitDevTools.extension\pyRevitDev.tab\Debug.panel\Engine Tests.pulldown\Test CPython Engine.pushbutton 
C:\Users\betsalel\AppData\Roaming\pyRevit-Master\extensions\pyRevitDevTools.extension\lib 
C:\Users\betsalel\AppData\Roaming\pyRevit-Master\extensions\pyRevitDevTools.extension\pyRevitDev.tab\Debug.panel\Engine Tests.pulldown\Test IronPython Search Paths.pushbutton\lib 
C:\Users\betsalel\AppData\Roaming\pyRevit-Master\extensions\pyRevitDevTools.extension\pyRevitDev.tab\Debug.panel\Engine Tests.pulldown\Test IronPython Search Paths.pushbutton\bin 
C:\Users\betsalel\AppData\Roaming\pyRevit-Master\extensions\pyRevitDevTools.extension\pyRevitDev.tab\Debug.panel\Engine Tests.pulldown\Test CPython Engine.pushbutton 
C:\Users\betsalel\AppData\Roaming\pyRevit-Master\pyrevitlib 
C:\Users\betsalel\AppData\Roaming\pyRevit-Master\site-packages 
C:\Users\betsalel\AppData\Roaming\pyRevit-Master\bin\netcore



IronPython Traceback:
Traceback (most recent call last):
 File "C:\Users\betsalel\AppData\Roaming\pyRevit-Master\extensions\pyRevitDevTools.extension\pyRevitDev.tab\Debug.panel\Engine Tests.pulldown\Test CPython Engine.pushbutton\script.py", line 28, in <module>
 File "C:\Users\betsalel\AppData\Roaming\pyRevit-Master\extensions\pyRevitDevTools.extension\pyRevitDev.tab\Debug.panel\Engine Tests.pulldown\Test CPython Engine.pushbutton\script.py", line 28, in <module>
SystemError: The type initializer for 'Delegates' threw an exception.

Script Executor Traceback:
System.TypeInitializationException: The type initializer for 'Delegates' threw an exception.
 ---> Python.Runtime.BadPythonDllException: Runtime.PythonDLL was not set or does not point to a supported Python runtime DLL. See https://github.com/pythonnet/pythonnet#embedding-python-in-net
 ---> System.MissingMethodException: Failed to load symbol Py_IncRef.
 ---> System.ComponentModel.Win32Exception (127): The specified procedure could not be found.
 --- End of inner exception stack trace ---
 at Python.Runtime.Platform.WindowsLoader.GetFunction(IntPtr hModule, String procedureName)
 at Python.Runtime.Runtime.Delegates.GetFunctionByName(String functionName, IntPtr libraryHandle)
 --- End of inner exception stack trace ---
 at Python.Runtime.Runtime.TryUsingDll[T](Func`1 op)
 at Python.Runtime.Runtime.Initialize(Boolean initSigs)
 at Python.Runtime.PythonEngine.Initialize(IEnumerable`1 args, Boolean setSysArgv, Boolean initSigs)
 at Python.Runtime.PythonEngine.Initialize(Boolean setSysArgv, Boolean initSigs)
 at Python.Runtime.PythonEngine.Initialize()
 at Microsoft.Scripting.Interpreter.ActionCallInstruction.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.LightLambda.Run3[T0,T1,T2,TRet](T0 arg0, T1 arg1, T2 arg2)
 at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
 at Microsoft.Scripting.Interpreter.DynamicInstruction`3.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.LightLambda.Run2[T0,T1,TRet](T0 arg0, T1 arg1)
 at IronPython.Compiler.PythonScriptCode.RunWorker(CodeContext ctx)
 at IronPython.Compiler.PythonScriptCode.Run(Scope scope)
 at IronPython.Compiler.RuntimeScriptCode.InvokeTarget(Scope scope)
 at Microsoft.Scripting.Hosting.CompiledCode.Execute(ScriptScope scope)
 at PyRevitLabs.PyRevit.Runtime.IronPythonEngine.Execute(ScriptRuntime& runtime)
 --- End of inner exception stack trace ---
 at Python.Runtime.Runtime.Delegates.get_PyErr_Clear()
 at Python.Runtime.Runtime.PyErr_Clear()
 at Python.Runtime.Exceptions.Clear()
 at Python.Runtime.PythonEngine.Initialize(IEnumerable`1 args, Boolean setSysArgv, Boolean initSigs)
 at Python.Runtime.PythonEngine.Initialize(Boolean setSysArgv, Boolean initSigs)
 at Python.Runtime.PythonEngine.Initialize()
 at Microsoft.Scripting.Interpreter.ActionCallInstruction.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.LightLambda.Run3[T0,T1,T2,TRet](T0 arg0, T1 arg1, T2 arg2)
 at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
 at Microsoft.Scripting.Interpreter.DynamicInstruction`3.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.LightLambda.Run2[T0,T1,TRet](T0 arg0, T1 arg1)
 at IronPython.Compiler.PythonScriptCode.RunWorker(CodeContext ctx)
 at IronPython.Compiler.PythonScriptCode.Run(Scope scope)
 at IronPython.Compiler.RuntimeScriptCode.InvokeTarget(Scope scope)
 at Microsoft.Scripting.Hosting.CompiledCode.Execute(ScriptScope scope)
 at PyRevitLabs.PyRevit.Runtime.IronPythonEngine.Execute(ScriptRuntime& runtime)
```

### ♻️ To Reproduce

Run "Test CPython command" or "Test CPython engine" form the Debug panel in pyRevitDev tab.

### ⏲️ Expected behavior

_No response_

### 🖥️ Hardware and Software Setup (please complete the following information)

```shell
==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive/image)
master | Branch: "master" | Version: "6.4.0.26100+0515" | Path: "C:\Users\betsalel\AppData\Roaming\pyRevit-Master"
==> Attachments
master | Product: "2026 First Customer Ship" | Engine: DEFAULT (2712) | Path: "C:\Users\betsalel\AppData\Roaming\pyRevit-Master"
==> Installed Extension
==> Default Extension Search Path
C:\Users\betsalel\AppData\Roaming\pyRevit\Extensions
==> Extension Search Paths
S:\BIM Utilities\pyRevit
==> Extension Sources - Default
https://github.com/pyrevitlabs/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
2026 First Customer Ship | Version: 26.0.4.409 | Build: 20250227_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2026\"
==> Running Revit Instances
PID: 26216 | 2026.4 | Version: 26.4.0.32 | Build: 20251103_1515(x64) | Language: 0 | Path: "C:\Program Files\Autodesk\Revit 2026"
==> User Environment
Microsoft Windows 10 [Version 10.0.26200]
Executing User: FEIGIN\Betsalel
Active User:
Admin Access: No
%APPDATA%: "C:\Users\betsalel\AppData\Roaming"
Latest Installed .Net Framework: 10.0.2
No .Net Target Packs are installed.
No .Net-Core Target Packs are installed.
Active CPython Engine Version: 3123
pyRevit CLI v6.4.0.26100+0515.06e6e8108e8aaccfbb7080163a437e19236a8533
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by tay0thman**
### Problem
 
All `#! python3` (CPython) scripts fail to execute under the new C# loader. The `Test CPython Command` button crashes Revit with "The type initializer for 'Delegates' threw an exception", and `Test CPython Engine` throws `BadPythonDllException: Runtime.PythonDLL was not set`.
 
### Root Cause
 
`EnvDictionarySeeder.cs` hardcodes `PYREVIT_CPYVERSION` as `"3.12.3"` (dotted version string). At runtime, `CPythonEngine.GetPythonDll()` calls `int.Parse(runtime.EngineVersion)` on this value, which throws `FormatException` because `"3.12.3"` is not a valid integer. The `PythonDLL` path is never set, and pythonnet's `Delegates` static initializer crashes.
 
The legacy Python loader sets this env var as `str(cpyengine.Version)` where `Version` is a `PyRevitEngineVersion(3123)` — an integer, not a dotted string.
 
### Fix
 
**`EnvDictionarySeeder.cs`**: Added `ReadCPYVersion()` method that dynamically resolves the CPython engine version by scanning `bin/cengines/CPY*` directories, returning the integer format (`"3123"`) that `int.Parse()` expects. Replaces the hardcoded `"3.12.3"`.
 
**`Test CPython Engine.pushbutton/script.py`**: Converted from IronPython-bootstrapped pythonnet to native `#! python3`. The old approach of manually loading `pyRevitLabs.PythonNet.dll` from IronPython and calling `PythonEngine.Initialize()` is no longer viable with the pythonnet 3.x fork — the `Delegates` static initializer fires before `Runtime.PythonDLL` can be set through IronPython's dynamic dispatch.
 
**`Test CPython Events.pushbutton/script.py`**: Removed `EventHandler[T]()` wrapper (IronPython pattern that fails in CPython). Uses direct `+=` event subscription which pythonnet 3.x handles automatically. Wrapped `-=` unsubscribe in try/except for the known pythonnet delegate identity limitation.
 
### Testing
 
- [x] `Test CPython Command` — executes, prints Python version, Revit API access, pyrevit imports, unicode
- [x] `Test CPython Engine` — executes, tests pythonnet interop, .NET types, eval/exec, Revit document access
- [x] `Test CPython Events` — subscribe succeeds, unsubscribe gracefully handled
- [x] IronPython buttons unaffected
- [x] Tested on Revit 2026 (NETCORE / .NET 8)
 
Fixes #3284

### CODE REVIEW

File: dev/pyRevitLoader/pyRevitAssemblyBuilder/SessionManager/EnvDictionarySeeder.cs [hunk 1]
```diff
@@ -189,5 +189,48 @@ internal static string ReadIPYVersion(string pyRevitRoot)
 
             return "Unknown";
         }
+        /// <summary>
+        /// Reads the CPython engine version as an integer string (e.g. "3123") to match
+        /// the legacy Python loader format: str(cpyengine.Version) where Version is
+        /// PyRevitEngineVersion(int).  The runtime's CPythonEngine.GetPythonDll() calls
+        /// int.Parse() on this value, so it MUST be a plain integer — not a dotted
+        /// version like "3.12.3".
+        /// Fix for CPython engine initialization failure.
```
Comment (sanzoghenzo) [inline dev/pyRevitLoader/pyRevitAssemblyBuilder/SessionManager/EnvDictionarySeeder.cs]: The documentation should describe what a function does, not what the other function uses it for or what was the previous behavior.
AI doesn't ever get this and always adds comparison about previous behaviour, which should be only stated in the commit and pr messages. Please instruct your agent to comply with this.

File: dev/pyRevitLoader/pyRevitAssemblyBuilder/SessionManager/EnvDictionarySeeder.cs [hunk 2]
```diff
@@ -189,5 +189,48 @@ internal static string ReadIPYVersion(string pyRevitRoot)
...
+            try
+            {
+                // CPython engines live under bin/cengines/CPY{version}/
+                // e.g. bin/cengines/CPY3123/ → version = 3123
+                var cenginesDir = Path.Combine(pyRevitRoot, "bin", "cengines");
+                if (!Directory.Exists(cenginesDir))
+                    return "0";
+
+                // Find the highest-versioned CPY directory (matches legacy behavior
+                // of returning the latest engine when no specific version is configured)
```
Comment (sanzoghenzo) [inline dev/pyRevitLoader/pyRevitAssemblyBuilder/SessionManager/EnvDictionarySeeder.cs]: Again, comment that mentions previous behaviour should not be there

File: dev/pyRevitLoader/pyRevitAssemblyBuilder/SessionManager/EnvDictionarySeeder.cs [hunk 3]
```diff
@@ -189,5 +189,48 @@ internal static string ReadIPYVersion(string pyRevitRoot)
...
+        internal static string ReadCPYVersion(string pyRevitRoot)
+        {
+            if (string.IsNullOrEmpty(pyRevitRoot))
+                return "0";
+
+            try
+            {
+                // CPython engines live under bin/cengines/CPY{version}/
+                // e.g. bin/cengines/CPY3123/ → version = 3123
+                var cenginesDir = Path.Combine(pyRevitRoot, "bin", "cengines");
```
Comment (sanzoghenzo) [inline dev/pyRevitLoader/pyRevitAssemblyBuilder/SessionManager/EnvDictionarySeeder.cs:204]: Just an open question: do we have other places where we build this path? Should we use a global object to refer to it and avoid having to change multiple code locations if this tirectory will move in the future?

File: dev/pyRevitLoader/pyRevitAssemblyBuilder/SessionManager/EnvDictionarySeeder.cs [hunk 4]
```diff
@@ -189,5 +189,48 @@ internal static string ReadIPYVersion(string pyRevitRoot)
...
+                if (!Directory.Exists(cenginesDir))
+                    return "0";
+
+                // Find the highest-versioned CPY directory (matches legacy behavior
+                // of returning the latest engine when no specific version is configured)
+                int maxVersion = 0;
+                foreach (var dir in Directory.GetDirectories(cenginesDir, "CPY*"))
+                {
+                    var dirName = Path.GetFileName(dir);
+                    if (dirName.StartsWith("CPY", StringComparison.OrdinalIgnoreCase)
```
Comment (sanzoghenzo) [inline dev/pyRevitLoader/pyRevitAssemblyBuilder/SessionManager/EnvDictionarySeeder.cs]: Is the check necessary? The GetDirectories method already returns the directories matching the pattern...

File: extensions/pyRevitDevTools.extension/pyRevitDev.tab/Debug.panel/Engine Tests.pulldown/Test CPython Engine.pushbutton/script.py [hunk 5]
```diff
@@ -1,57 +1,84 @@
-"""Test pythonnet integration"""
+#! python3
+"""Test CPython engine and pythonnet integration.
+
+Originally this script ran under IronPython and manually bootstrapped
+pythonnet to test cross-engine interop. With pyRevitLabs.PythonNet 3.x,
+that bootstrap is no longer possible (Delegates static initializer requires
+Runtime.PythonDLL + LoadLibrary before any type access). Converted to run
+natively on the CPython engine which handles initialization correctly via
+CPythonEngine.GetPythonDll().
```
Comment (sanzoghenzo) [inline extensions/pyRevitDevTools.extension/pyRevitDev.tab/Debug.panel/Engine Tests.pulldown/Test CPython Engine.pushbutton/script.py]: Documen what it does, not what it did!!!!

File: extensions/pyRevitDevTools.extension/pyRevitDev.tab/Debug.panel/Engine Tests.pulldown/Test CPython Events.pushbutton/script.py
Comment (sanzoghenzo) [inline extensions/pyRevitDevTools.extension/pyRevitDev.tab/Debug.panel/Engine Tests.pulldown/Test CPython Events.pushbutton/script.py:1]: Are this edits needed for solving the issue targeted by this PR? If not, address it into a separate one

**Review by sanzoghenzo — CHANGES_REQUESTED** [review]
Feeling more and more like a Don Quijote against AI slop 🤣 

The code is almost OK from a quick look at it, the comments are those driving me crazy 😅

**Comment by jmcouffin** [comment]
@sanzoghenzo 'de la mancha'

**Comment by tay0thman** [comment]
@sanzoghenzo I am going to clean it up, these edits were part of the overall cpython handling fix with the new loader. and I agree of these blaming comments are not helpful.
Also there is a version mismatch that I need to recompile and push another commit. should happen soon.

File: dev/pyRevitLoader/pyRevitAssemblyBuilder/SessionManager/EnvDictionarySeeder.cs (hunk 1 above)
Comment (tay0thman) [reply dev/pyRevitLoader/pyRevitAssemblyBuilder/SessionManager/EnvDictionarySeeder.cs]: I will clean this mess

File: dev/pyRevitLoader/pyRevitAssemblyBuilder/SessionManager/EnvDictionarySeeder.cs (hunk 3 above)
Comment (tay0thman) [reply dev/pyRevitLoader/pyRevitAssemblyBuilder/SessionManager/EnvDictionarySeeder.cs:204]: I think we can centralize it under `pyRevitLabs.PyRevit/ PyRevitClone.cs` ,this fix simply being consistent with the existing `ReadIPYVersion()` but I agree or restructuring the paths around global objects.

File: dev/pyRevitLoader/pyRevitAssemblyBuilder/SessionManager/EnvDictionarySeeder.cs (hunk 4 above)
Comment (tay0thman) [reply dev/pyRevitLoader/pyRevitAssemblyBuilder/SessionManager/EnvDictionarySeeder.cs]: No it is redundant, I'll remove it

File: extensions/pyRevitDevTools.extension/pyRevitDev.tab/Debug.panel/Engine Tests.pulldown/Test CPython Events.pushbutton/script.py
Comment (tay0thman) [reply extensions/pyRevitDevTools.extension/pyRevitDev.tab/Debug.panel/Engine Tests.pulldown/Test CPython Events.pushbutton/script.py:1]: I'm going move the Test Events to another PR, agree on that.

**Comment by tay0thman** [comment]
Pushed a new commit, removed extra comments from copilot, also removed the Cpython Test Events from this PR, it will be fixed under a separate PR.

File: dev/pyRevitLoader/pyRevitAssemblyBuilder/SessionManager/EnvDictionarySeeder.cs [hunk 6]
```diff
@@ -189,5 +189,37 @@ internal static string ReadIPYVersion(string pyRevitRoot)
...
+        internal static string ReadCPYVersion(string pyRevitRoot)
+        {
+            if (string.IsNullOrEmpty(pyRevitRoot))
+                return "0";
+
+            try
+            {
+                var cenginesDir = Path.Combine(pyRevitRoot, "bin", "cengines");
+                if (!Directory.Exists(cenginesDir))
+                    return "0";
```
[the remark this answers is not in the document]
Comment (tay0thman) [reply dev/pyRevitLoader/pyRevitAssemblyBuilder/SessionManager/EnvDictionarySeeder.cs:206]: Returning "0" matches the legacy Python behavior — sessioninfo.py line 66 sets CPYVERSION_ENVVAR to "0" when the engine can't be resolved. ReadIPYVersion() in the same file follows the same pattern. If pyRevitRoot fails to resolve, CPython is genuinely unavailable — returning a fake version would just move the crash downstream. The FindPyRevitRoot hardening is tracked separately under #3108.

File: dev/pyRevitLoader/pyRevitAssemblyBuilder/SessionManager/EnvDictionarySeeder.cs [hunk 7]
```diff
@@ -189,5 +189,37 @@ internal static string ReadIPYVersion(string pyRevitRoot)
...
+                int maxVersion = 0;
+                foreach (var dir in Directory.GetDirectories(cenginesDir, "CPY*"))
+                {
+                    var dirName = Path.GetFileName(dir);
+                    if (int.TryParse(dirName.Substring(3), out int ver) && ver > maxVersion)
+                        maxVersion = ver;
+                }
+
+                return maxVersion > 0 ? maxVersion.ToString() : "0";
+            }
```
[the remark this answers is not in the document]
Comment (tay0thman) [reply dev/pyRevitLoader/pyRevitAssemblyBuilder/SessionManager/EnvDictionarySeeder.cs:217]: Fair point. ReadCPYVersion follows the same pattern as ReadIPYVersion and ReadPyRevitVersion in this file — neither has unit tests either. Adding test coverage for all three is worth doing but out of scope for this bug fix. Can track as a follow-up PR.

File: dev/pyRevitLoader/pyRevitAssemblyBuilder/SessionManager/EnvDictionarySeeder.cs [hunk 8]
```diff
@@ -69,7 +69,7 @@ public static void Seed(UIApplication uiApp, Assembly runtimeAssembly, string py
                 [KeyVersion]            = ReadPyRevitVersion(pyRevitRoot),
                 [KeyClone]              = "Unknown",
                 [KeyIPYVersion]         = ReadIPYVersion(pyRevitRoot),
-                [KeyCPYVersion]         = "3.12.3",    // Known default for the bundled CPython engine
+                [KeyCPYVersion]         = ReadCPYVersion(pyRevitRoot),
 
                 // Fix for #3203: PyRevitConfig.LoggingLevel returns a pyRevit enum
                 // (0=Quiet, 1=Verbose, 2=Debug) but the Python logger reads this
```
[the remark this answers is not in the document]
Comment (tay0thman) [reply dev/pyRevitLoader/pyRevitAssemblyBuilder/SessionManager/EnvDictionarySeeder.cs:75]: Test Cpython Events fixes has been pushed to another PR.

File: extensions/pyRevitDevTools.extension/pyRevitDev.tab/Debug.panel/Engine Tests.pulldown/Test CPython Engine.pushbutton/script.py [hunk 9]
```diff
@@ -1,57 +1,77 @@
...
+print('json: {}'.format(json.dumps({"test": True})))
+import pathlib
+print('pathlib: {}'.format(pathlib.Path(os.getcwd())))
+
+# Test unicode
+print('\n## unicode:')
+print('Cyrillic: \u041a\u0438\u0440\u0438\u043b\u043b\u0438\u0446\u0430')
+print('CJK: \u4f60\u597d\u4e16\u754c')
+
+print('\n## All tests passed.')
```
[the remark this answers is not in the document]
Comment (tay0thman) [reply extensions/pyRevitDevTools.extension/pyRevitDev.tab/Debug.panel/Engine Tests.pulldown/Test CPython Engine.pushbutton/script.py:77]: The document section is wrapped in try/except by design — it's optional since the script runs in zero-doc context. The output already shows 'Document test skipped: {reason}' when it catches, so the results are clear.

**Review by jmcouffin — APPROVED** [review]

**Review by jmcouffin — APPROVED** [review]

**Comment by jmcouffin** [comment]
:package: New public release is available for [6.5.0.26173+1406](https://github.com/pyrevitlabs/pyRevit/releases/tag/v6.5.0.26173%2B1406)
